export { default as Jumbotron } from "./jumbotron";
export { default as Footer } from "./footer";
export { default as Accordian } from "./accordian";
export { default as OptForm } from "./opt-form";
export { default as Header } from "./Header";
export { default as HeroHome } from "./HeroHome";
export { default as Form } from "./Sign-form";
export { default as Profiles } from "./profile";
export { default as Loading } from "./loading";
